{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "circuit-breaker-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}